server:
  port: 7003
management:
  security:
    enabled: false
consul-java-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 1
    MaxAutoRetriesNextSerer: 1
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.thoughtworks.study.springcloudconfig.client.FeignUserResource: DEBUG