spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yourwafer/spring-cloud-demo.git
          searchPaths: ./config-resource
server:
  port: 7006
# git管理配置
debug: false
encrypt:
  key: ConfigServer
management:
  security:
    enabled: false